name: ci-test

on: 
    push: 
        branches: ["main"]
    pull_request: 
        branches: ["main"]


jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: ^1.23.1
              id: go

            - name: Check out code with Go module repository
              uses: actions/checkout@v4

            - name: Run tests
              run: make test